services:
  postgres:
    image: postgres:15
    container_name: langgraph-postgres
    environment:
      POSTGRES_DB: langgraph
      POSTGRES_USER: langgraph_user
      POSTGRES_PASSWORD: langgraph_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langgraph_user -d langgraph"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
